name: 'avatest.testivaylapilvi.fi testing' 
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    name: Artifacts
    steps:
      - uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - uses: cypress-io/github-action@v5 # use the explicit version number
        env:
          REACT_APP_FOLDERS_URL: https://apiavatest.testivaylapilvi.fi/v2/ava/hakemisto/
          REACT_APP_INST_URL: https://apiavatest.testivaylapilvi.fi/ava/ohjeluettelo
          REACT_APP_S3_OHJEET_ENDPOINT: https://avatest.testivaylapilvi.fi/ava/Ohjeluettelo/
        with:
          build: npm run build:test
          start: npm run start
      # after the test run completes
      # store videos and any screenshots
      # NOTE: screenshots will be generated only if E2E test failed
      # thus we store screenshots only on failures
      # Alternative: create and commit an empty cypress/screenshots folder
      # to always have something to upload
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
